import '../models/profile_model.dart';
import '../models/spot_model.dart';
import '../models/restaurant_model.dart';
import '../models/discount_code_model.dart';
import '../models/guide_model.dart';
import '../models/review_model.dart';
import '../models/notification_model.dart';

class SeedDataService {
  static List<ProfileModel> getInitialProfiles() => [
    ProfileModel(
      id: 'usr-tourist-1',
      email: 'tourist@livelocal.my',
      fullName: 'Alex Tan (Tourist)',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      role: 'tourist',
    ),
    ProfileModel(
      id: 'usr-influencer-1',
      email: 'foodie@livelocal.my',
      fullName: 'KL Foodie (Influencer)',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      role: 'influencer',
    ),
    ProfileModel(
      id: 'usr-admin-1',
      email: 'admin@livelocal.my',
      fullName: 'Admin User',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      role: 'admin',
    ),
  ];

  static List<SpotModel> getInitialSpots() => [
    SpotModel(
      id: 'spot-001',
      name: 'Kek Lok Si Temple Hilltop',
      category: 'Heritage Site',
      description: 'The largest Buddhist temple in Malaysia, terraced up Air Itam hill with the seven-storey Pagoda of Ten Thousand Buddhas and a towering Kuan Yin statue overlooking George Town.',
      state: 'Penang',
      city: 'Air Itam',
      address: '1000 Jalan Balik Pulau, 11500 Air Itam, Pulau Pinang',
      priceRange: '\$',
      bestTime: '8:30 AM - 11:30 AM',
      thingsToDo: 'Climb the Pagoda, ride the incline lift, see the Kuan Yin statue',
      imageUrl: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=600',
      rating: 4.8,
      reviewCount: 42,
      submittedBy: 'usr-tourist-1',
      status: 'approved',
    ),
    SpotModel(
      id: 'spot-002',
      name: 'Bukit Kiara Trail Lookout',
      category: 'Nature & Parks',
      description: 'A shaded jungle trail network that KL residents hike every weekend, ending at a ridge lookout with an open view over the TTDI skyline.',
      state: 'Kuala Lumpur',
      city: 'Taman Tun Dr Ismail',
      address: 'Jalan Bukit Kiara, TTDI, 60000 Kuala Lumpur',
      priceRange: '\$',
      bestTime: '6:30 AM - 9:30 AM',
      thingsToDo: 'Hike the ridge trail, birdwatching, sunrise photography',
      imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600',
      rating: 4.6,
      reviewCount: 29,
      submittedBy: 'usr-tourist-1',
      status: 'approved',
    ),
    SpotModel(
      id: 'spot-003',
      name: 'Ipoh Mural Art Trail',
      category: 'Street Art',
      description: 'A walking trail of large-scale murals painted across pre-war shoplot walls in Ipoh Old Town, documenting the city\'s tin-mining and kopitiam heritage.',
      state: 'Perak',
      city: 'Ipoh',
      address: 'Jalan Sultan Yussuf & Market Lane, 30000 Ipoh, Perak',
      priceRange: '\$',
      bestTime: '8:00 AM - 11:00 AM',
      thingsToDo: 'Photograph the murals, explore Concubine Lane alleys',
      imageUrl: 'https://images.unsplash.com/photo-1499363536502-87642509e31b?w=600',
      rating: 4.7,
      reviewCount: 35,
      submittedBy: 'usr-influencer-1',
      status: 'approved',
    ),
    SpotModel(
      id: 'spot-004',
      name: 'Johor Bahru Chinese Heritage Museum',
      category: 'Museum & Gallery',
      description: 'A compact community museum on Jalan Ibrahim tracing the five Chinese clans that built Johor Bahru, with restored artefacts, photographs and the annual Chingay parade collection.',
      state: 'Johor',
      city: 'Johor Bahru',
      address: '42 Jalan Ibrahim, 80000 Johor Bahru, Johor',
      priceRange: '\$\$',
      bestTime: '9:00 AM - 5:00 PM',
      thingsToDo: 'View the Chingay parade gallery and clan history exhibits',
      imageUrl: 'https://images.unsplash.com/photo-1566127992631-137a642a90f4?w=600',
      rating: 4.5,
      reviewCount: 18,
      submittedBy: 'usr-tourist-1',
      status: 'approved',
    ),
    SpotModel(
      id: 'spot-005',
      name: 'Melaka River Heritage Walk',
      category: 'Cultural Landmark',
      description: 'A riverside promenade winding past Dutch-era warehouses, painted shophouse walls and Kampung Morten stilt houses in the heart of UNESCO-listed Melaka.',
      state: 'Melaka',
      city: 'Melaka City',
      address: 'Jalan Tun Sri Lanang, 75300 Melaka',
      priceRange: '\$',
      bestTime: '5:00 PM - 8:00 PM',
      thingsToDo: 'Walk the riverfront murals, ride the river cruise, visit Kampung Morten',
      imageUrl: 'https://images.unsplash.com/photo-1585504198199-20277593b94f?w=600',
      rating: 4.6,
      reviewCount: 31,
      submittedBy: 'usr-tourist-1',
      status: 'approved',
    ),
    SpotModel(
      id: 'spot-006',
      name: 'Batu Caves Temple Steps',
      category: 'Heritage Site',
      description: 'A 400-million-year-old limestone hill with a golden Murugan statue guarding 272 rainbow-painted steps up to the Cathedral Cave shrine.',
      state: 'Selangor',
      city: 'Gombak',
      address: 'Jalan Batu Caves, 68100 Batu Caves, Selangor',
      priceRange: '\$',
      bestTime: '7:00 AM - 10:00 AM',
      thingsToDo: 'Climb the 272 steps, visit Cathedral Cave, watch the macaques',
      imageUrl: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=600',
      rating: 4.7,
      reviewCount: 58,
      submittedBy: 'usr-influencer-1',
      status: 'approved',
    ),
    SpotModel(
      id: 'spot-007',
      name: 'Tanjung Aru Sunset Beach',
      category: 'Viewpoint',
      description: 'Kota Kinabalu\'s favourite evening spot, where locals gather on the sand for grilled snacks and one of Borneo\'s best sunsets over the South China Sea.',
      state: 'Sabah',
      city: 'Kota Kinabalu',
      address: 'Jalan Aru, Tanjung Aru, 88100 Kota Kinabalu, Sabah',
      priceRange: '\$',
      bestTime: '5:30 PM - 7:30 PM',
      thingsToDo: 'Watch the sunset, beachside street snacks, island views',
      imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600',
      rating: 4.8,
      reviewCount: 47,
      submittedBy: 'usr-tourist-1',
      status: 'approved',
    ),
    SpotModel(
      id: 'spot-008',
      name: 'Kuching Waterfront & Sarawak Museum Walk',
      category: 'Museum & Gallery',
      description: 'A riverside stroll linking the Kuching Waterfront esplanade to the Borneo Cultures Museum, showcasing Sarawak\'s indigenous heritage and colonial landmarks.',
      state: 'Sarawak',
      city: 'Kuching',
      address: 'Jalan Tun Abang Haji Openg, 93000 Kuching, Sarawak',
      priceRange: '\$\$',
      bestTime: '9:00 AM - 12:00 PM',
      thingsToDo: 'Tour the Borneo Cultures Museum, cross by sampan, see the Astana',
      imageUrl: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?w=600',
      rating: 4.5,
      reviewCount: 22,
      submittedBy: 'usr-influencer-1',
      status: 'approved',
    ),
    SpotModel(
      id: 'spot-009',
      name: 'Perdana Botanical Garden Lake Loop',
      category: 'Nature & Parks',
      description: 'KL\'s oldest public park in the Lake Gardens, with a lakeside jogging loop, hibiscus garden and shaded boardwalks minutes from the city centre.',
      state: 'Kuala Lumpur',
      city: 'Tasik Perdana',
      address: 'Jalan Kebun Bunga, Tasik Perdana, 55100 Kuala Lumpur',
      priceRange: '\$',
      bestTime: '7:00 AM - 10:00 AM',
      thingsToDo: 'Lake loop walk, hibiscus and orchid gardens, picnic lawns',
      imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600',
      rating: 4.4,
      reviewCount: 26,
      submittedBy: 'usr-tourist-1',
      status: 'approved',
    ),
    SpotModel(
      id: 'spot-010',
      name: 'Armenian Street Mural Corner',
      category: 'Street Art',
      description: 'The George Town street art cluster around Lebuh Armenian, home to the famous "Kids on Bicycle" mural and wrought-iron caricature trail.',
      state: 'Penang',
      city: 'George Town',
      address: 'Lebuh Armenian, 10200 George Town, Pulau Pinang',
      priceRange: '\$',
      bestTime: '8:00 AM - 10:30 AM',
      thingsToDo: 'Photograph the murals, follow the iron caricature trail',
      imageUrl: 'https://images.unsplash.com/photo-1555921015-5532091f6026?w=600',
      rating: 4.6,
      reviewCount: 39,
      submittedBy: 'usr-influencer-1',
      status: 'pending',
    ),
  ];



  static List<RestaurantModel> getInitialRestaurants() => [
    RestaurantModel(
      id: 'rest-001',
      name: 'Ah Hock Hawker Fried Kuey Teow',
      address: '34 Jalan Burmah, George Town, Penang',
      state: 'Penang',
      city: 'George Town',
      cuisineType: 'Hawker Street Food',
      priceRange: '\$',
      reviewedDishes: 'Duck Egg Char Kuey Teow, Fried Oyster Omelette',
      influencerId: 'usr-influencer-1',
      influencerName: 'KL Foodie',
      socialMediaUrl: 'https://www.tiktok.com/@klfoodie/video/123456789',
      coverPhotoUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600',
    ),
    RestaurantModel(
      id: 'rest-002',
      name: 'Restoran Nasi Kandar Line Clear (Local Secret Branch)',
      address: '17 Jalan Penang, George Town, Penang',
      state: 'Penang',
      city: 'George Town',
      cuisineType: 'Nasi Kandar',
      priceRange: '\$\$',
      reviewedDishes: 'Ayam Goreng Spiced, Sotong Besar, Kuah Campur',
      influencerId: 'usr-influencer-1',
      influencerName: 'Penang Eats',
      socialMediaUrl: 'https://www.instagram.com/p/C123456789/',
      coverPhotoUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600',
    ),
    RestaurantModel(
      id: 'rest-003',
      name: 'Kopitiam Sin Yoon Loong',
      address: '155 Jalan Dato Bandar Sugumaran, Ipoh, Perak',
      state: 'Perak',
      city: 'Ipoh',
      cuisineType: 'Traditional Malaysian Kopitiam',
      priceRange: '\$',
      reviewedDishes: 'Ipoh White Coffee, Chee Cheong Fun with Chili Paste',
      influencerId: 'usr-influencer-1',
      influencerName: 'Foodie Explorer MY',
      socialMediaUrl: 'https://www.tiktok.com/@foodieexplorer/video/987654321',
      coverPhotoUrl: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=600',
    ),
  ];

  static List<DiscountCodeModel> getInitialDiscountCodes() => [
    DiscountCodeModel(
      id: 'disc-001',
      restaurantId: 'rest-001',
      code: 'LIVELOCAL10',
      description: 'Get 10% OFF any Char Kuey Teow order when showing LiveLocal App',
      expiryDate: DateTime.now().add(const Duration(days: 60)),
      createdBy: 'usr-influencer-1',
    ),
    DiscountCodeModel(
      id: 'disc-002',
      restaurantId: 'rest-002',
      code: 'KLFOODIESPECIAL',
      description: 'Free Sirap Bandung drink with any Nasi Kandar set purchase',
      expiryDate: DateTime.now().add(const Duration(days: 30)),
      createdBy: 'usr-influencer-1',
    ),
  ];

  static List<GuideModel> getInitialGuides() => [
    GuideModel(
      id: 'guide-001',
      title: 'Sunday Morning TTDI Local Neighborhood Trail',
      locationName: 'Taman Tun Dr Ismail',
      state: 'Kuala Lumpur',
      routeOverview: 'Experience how KL locals spend a relaxing Sunday morning — from wet market rojak to quiet neighborhood park walks and indie artisanal coffee.',
      stops: [
        'TTDI Market Rojak Stall',
        'Lembah Kiara Recreation Park',
        'Kopitiam Kok Yuen',
        'Artisan Coffee Roasters TTDI'
      ],
      walkingSequence: [
        '1. Start at TTDI Market at 8:00 AM for fresh breakfast',
        '2. Walk 5 mins to Lembah Kiara Park for a refreshing shaded stroll',
        '3. Head to Kopitiam Kok Yuen at 10:30 AM for local coffee & toast',
        '4. Wrap up at Artisan Coffee Roasters for neighborhood vibe'
      ],
      estimatedDuration: '3.5 Hours',
      status: 'approved',
    ),
    GuideModel(
      id: 'guide-002',
      title: 'Ipoh Old Town Heritage & Coffee Crawl',
      locationName: 'Ipoh Old Town',
      state: 'Perak',
      routeOverview: 'Walk through historic pre-war shoplots, mural alleys, and iconic white coffee spots favored by Ipoh residents.',
      stops: [
        'Concubine Lane Heritage Walk',
        'Sin Yoon Loong Kopitiam',
        'Ipoh Railway Station Gardens',
        'Nam Heong White Coffee'
      ],
      walkingSequence: [
        '1. Start at Concubine Lane at 9:00 AM before crowd arrives',
        '2. Enjoy authentic White Coffee at Sin Yoon Loong',
        '3. Walk through mural alleys toward Railway Gardens',
        '4. Enjoy famous Egg Tarts at Nam Heong'
      ],
      estimatedDuration: '4 Hours',
      status: 'approved',
    ),
  ];

  static List<ReviewModel> getInitialReviews() => [
    ReviewModel(
      id: 'rev-001',
      spotId: 'spot-001',
      userId: 'usr-tourist-1',
      userName: 'Alex Tan',
      rating: 5.0,
      comment: 'Incredible hilltop views and the pagoda climb is worth it. Go early — it is quiet and cool before the crowds.',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    ReviewModel(
      id: 'rev-002',
      restaurantId: 'rest-001',
      userId: 'usr-tourist-1',
      userName: 'Alex Tan',
      rating: 4.5,
      comment: 'Used the LIVELOCAL10 discount code here and got 10% off! The duck egg char kuey teow had amazing wok hei.',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
  ];

  static List<NotificationModel> getInitialNotifications() => [
    NotificationModel(
      id: 'notif-001',
      userId: 'usr-tourist-1',
      title: 'New Local Spot Approved!',
      message: 'Kek Lok Si Temple Hilltop in Penang is now live on LiveLocal.',
      type: 'spot_approved',
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
    ),
    NotificationModel(
      id: 'notif-002',
      userId: 'usr-tourist-1',
      title: 'Exclusive Discount Code Alert',
      message: 'KL Foodie added a 10% discount code for Ah Hock Hawker CKT in Penang!',
      type: 'discount_alert',
      createdAt: DateTime.now().subtract(const Duration(hours: 1)),
    ),
  ];
}
